In [1]:
import os

folder_path = 'benchmarks/results' 
files = os.listdir(folder_path)
print(files)

['20260318_145955', '20260314_195539', '20260316_020327', '20260318_164756', '20260312_103401']

In [2]:
import pandas as pd
import glob

# csv_files = glob.glob(os.path.join(folder_path, '**', '*.csv'), recursive=True)
# print("CSV files found:", csv_files)

csv_files = ['benchmarks/results/20260318_145955/summary.csv', 'benchmarks/results/20260318_164756/summary.csv']

combined_df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

In [3]:
combined_df = combined_df.drop(columns=['batch_size', 'block_size', 'decode_mode', 'gen_length', 'model_path', 'offload_dir',
                                        'prompt_mode', 'raw_stdout', 'repetitions', 'target_context_len', 'threshold',
                                        'trace_dir', 'use_torch_profiler', 'warmup'])
combined_df

,do_compile,max_mem_alloc_mb,max_mem_reserved_mb,model_key,per_token_time_ms,prompt_len,run_type,tokens_per_s,total_time_s
0,True,3942.153320,4530.0,qwen,48.107190,128,baseline,20.786914,6.157720
1,True,3942.153320,4530.0,qwen,60.924656,128,profiled,16.413716,7.798356
2,True,3971.157715,4582.0,qwen,49.770664,256,baseline,20.092157,6.370645
3,True,3971.157715,4582.0,qwen,61.493253,256,profiled,16.261947,7.871136
4,True,4031.433594,4526.0,qwen,53.516373,512,baseline,18.685870,6.850096
5,True,4031.433594,4526.0,qwen,62.249069,512,profiled,16.064497,7.967881
6,True,4145.182617,4472.0,qwen,59.833819,1024,baseline,16.712956,7.658729
7,True,4145.182617,4472.0,qwen,64.010170,1024,profiled,15.622518,8.193302
8,True,4377.215820,4472.0,qwen,73.723249,2048,baseline,13.564242,9.436576
9,True,4377.215820,4472.0,qwen,75.203079,2048,profiled,13.297328,9.625994
10,True,4841.946289,5036.0,qwen,105.210031,4096,baseline,9.504797,13.466884
11,True,4841.946289,5036.0,qwen,106.120997,4096,profiled,9.423206,13.583488
12,True,3003.943848,3448.0,fast_dllm,24.846691,128,baseline,40.246808,3.180376
13,True,3003.943848,3448.0,fast_dllm,33.925123,128,profiled,29.476680,4.342416
14,True,3044.843750,3458.0,fast_dllm,19.822984,256,baseline,50.446491,2.537342
15,True,3044.843750,3458.0,fast_dllm,26.189475,256,profiled,38.183278,3.352253
16,True,3126.791016,3476.0,fast_dllm,36.096145,512,baseline,27.703790,4.620307
17,True,3126.791016,3476.0,fast_dllm,45.192692,512,profiled,22.127471,5.784665
18,True,3290.685547,3522.0,fast_dllm,44.435082,1024,baseline,22.504741,5.687691
19,True,3290.685547,3522.0,fast_dllm,52.134319,1024,profiled,19.181223,6.673193
20,True,3624.132812,4098.0,fast_dllm,63.191379,2048,baseline,15.824943,8.088497
21,True,3622.492188,4098.0,fast_dllm,66.228435,2048,profiled,15.099255,8.477240
22,True,4292.335938,4636.0,fast_dllm,95.406880,4096,baseline,10.481424,12.212081
23,True,4290.695312,4636.0,fast_dllm,97.388686,4096,profiled,10.268133,12.465752
24,False,3914.370117,4504.0,qwen,99.925749,128,baseline,10.007431,12.790496
25,False,3914.370117,4504.0,qwen,168.003819,128,profiled,5.952246,21.504489
26,False,3929.374023,4530.0,qwen,95.328534,256,baseline,10.490039,12.202052
27,False,3929.374023,4530.0,qwen,185.236691,256,profiled,5.398499,23.710296
28,False,3984.837891,4530.0,qwen,96.414906,512,baseline,10.371840,12.341108
29,False,3984.837891,4530.0,qwen,173.597563,512,profiled,5.760450,22.220488
30,False,4048.416504,4472.0,qwen,97.556307,1024,baseline,10.250491,12.487207
31,False,4048.416504,4472.0,qwen,164.534565,1024,profiled,6.077750,21.060424
32,False,4212.955566,4474.0,qwen,106.361842,2048,baseline,9.401868,13.614316
33,False,4212.955566,4474.0,qwen,172.017786,2048,profiled,5.813352,22.018277
34,False,4542.033691,4616.0,qwen,131.465472,4096,baseline,7.606560,16.827580
35,False,4542.033691,4616.0,qwen,180.529217,4096,profiled,5.539270,23.107740
36,False,3003.870117,3448.0,fast_dllm,39.876832,128,baseline,25.077218,5.104235
37,False,3003.870117,3448.0,fast_dllm,76.188400,128,profiled,13.125358,9.752115
38,False,3044.843750,3454.0,fast_dllm,50.249716,256,baseline,19.900610,6.431964
39,False,3044.843750,3454.0,fast_dllm,94.415387,256,profiled,10.591494,12.085169
40,False,3126.791016,3458.0,fast_dllm,52.408951,512,baseline,19.080710,6.708346
41,False,3126.791016,3458.0,fast_dllm,99.650831,512,profiled,10.035039,12.755306
42,False,3290.685547,3488.0,fast_dllm,61.248750,1024,baseline,16.326864,7.839840
43,False,3290.685547,3488.0,fast_dllm,107.023033,1024,profiled,9.343783,13.698948
44,False,3624.595215,4098.0,fast_dllm,76.774088,2048,baseline,13.025228,9.827083
45,False,3624.595215,4098.0,fast_dllm,135.794204,2048,profiled,7.364085,17.381658
46,False,4294.860840,4636.0,fast_dllm,116.271656,4096,baseline,8.600548,14.882772
47,False,4294.860840,4636.0,fast_dllm,150.003651,4096,profiled,6.666504,19.200467

In [4]:
raw_df = combined_df[combined_df['run_type'] == 'baseline']
raw_df.drop(columns=['run_type'])

,do_compile,max_mem_alloc_mb,max_mem_reserved_mb,model_key,per_token_time_ms,prompt_len,tokens_per_s,total_time_s
0,True,3942.153320,4530.0,qwen,48.107190,128,20.786914,6.157720
2,True,3971.157715,4582.0,qwen,49.770664,256,20.092157,6.370645
4,True,4031.433594,4526.0,qwen,53.516373,512,18.685870,6.850096
6,True,4145.182617,4472.0,qwen,59.833819,1024,16.712956,7.658729
8,True,4377.215820,4472.0,qwen,73.723249,2048,13.564242,9.436576
10,True,4841.946289,5036.0,qwen,105.210031,4096,9.504797,13.466884
12,True,3003.943848,3448.0,fast_dllm,24.846691,128,40.246808,3.180376
14,True,3044.843750,3458.0,fast_dllm,19.822984,256,50.446491,2.537342
16,True,3126.791016,3476.0,fast_dllm,36.096145,512,27.703790,4.620307
18,True,3290.685547,3522.0,fast_dllm,44.435082,1024,22.504741,5.687691
20,True,3624.132812,4098.0,fast_dllm,63.191379,2048,15.824943,8.088497
22,True,4292.335938,4636.0,fast_dllm,95.406880,4096,10.481424,12.212081
24,False,3914.370117,4504.0,qwen,99.925749,128,10.007431,12.790496
26,False,3929.374023,4530.0,qwen,95.328534,256,10.490039,12.202052
28,False,3984.837891,4530.0,qwen,96.414906,512,10.371840,12.341108
30,False,4048.416504,4472.0,qwen,97.556307,1024,10.250491,12.487207
32,False,4212.955566,4474.0,qwen,106.361842,2048,9.401868,13.614316
34,False,4542.033691,4616.0,qwen,131.465472,4096,7.606560,16.827580
36,False,3003.870117,3448.0,fast_dllm,39.876832,128,25.077218,5.104235
38,False,3044.843750,3454.0,fast_dllm,50.249716,256,19.900610,6.431964
40,False,3126.791016,3458.0,fast_dllm,52.408951,512,19.080710,6.708346
42,False,3290.685547,3488.0,fast_dllm,61.248750,1024,16.326864,7.839840
44,False,3624.595215,4098.0,fast_dllm,76.774088,2048,13.025228,9.827083
46,False,4294.860840,4636.0,fast_dllm,116.271656,4096,8.600548,14.882772

In [5]:
baseline_df = combined_df[combined_df['run_type'] == 'baseline'].copy()
index_cols = ['prompt_len']
metric_order = [
    'total_time_s',
    # 'per_token_time_ms',
    'tokens_per_s',
    'max_mem_alloc_mb',
    'max_mem_reserved_mb',
]

models_df_dict = {}
def get_speedup(metric, a, b):
    match metric:
        case 'total_time_s': return a / b
        case _: return b / a 

for model_key in sorted(baseline_df['model_key'].unique()):
    model_df = baseline_df[baseline_df['model_key'] == model_key].copy()

    baseline_table = (
        model_df[model_df['do_compile'] == False]
        .drop(columns=['model_key', 'run_type', 'do_compile'])
        .set_index(index_cols)
        .sort_index()
    )
    compiled_table = (
        model_df[model_df['do_compile'] == True]
        .drop(columns=['model_key', 'run_type', 'do_compile'])
        .set_index(index_cols)
        .sort_index()
    )

    common_index = baseline_table.index.intersection(compiled_table.index)
    baseline_table = baseline_table.loc[common_index]
    compiled_table = compiled_table.loc[common_index]

    metrics = [
        metric for metric in metric_order
        if metric in baseline_table.columns and metric in compiled_table.columns
    ]

    comparison_table = pd.concat(
        {
            metric: pd.DataFrame(
                {
                    'baseline': baseline_table[metric],
                    'compiled': compiled_table[metric],
                    'speedup': get_speedup(metric, baseline_table[metric], compiled_table[metric]),
                }
            )
            for metric in metrics
        },
        axis=1,
    )
    models_df_dict[model_key] = comparison_table

In [6]:
models_df_dict.keys()

dict_keys(['fast_dllm', 'qwen'])

In [7]:
models_df_dict['fast_dllm'].round(2)

           total_time_s                  tokens_per_s                   \
               baseline compiled speedup     baseline compiled speedup
prompt_len
128                5.10     3.18    1.60        25.08    40.25    1.60
256                6.43     2.54    2.53        19.90    50.45    2.53
512                6.71     4.62    1.45        19.08    27.70    1.45
1024               7.84     5.69    1.38        16.33    22.50    1.38
2048               9.83     8.09    1.21        13.03    15.82    1.21
4096              14.88    12.21    1.22         8.60    10.48    1.22

           max_mem_alloc_mb                  max_mem_reserved_mb           \
                   baseline compiled speedup            baseline compiled
prompt_len
128                 3003.87  3003.94     1.0              3448.0   3448.0
256                 3044.84  3044.84     1.0              3454.0   3458.0
512                 3126.79  3126.79     1.0              3458.0   3476.0
1024                3290.69  3290.69     1.0              3488.0   3522.0
2048                3624.60  3624.13     1.0              4098.0   4098.0
4096                4294.86  4292.34     1.0              4636.0   4636.0


           speedup
prompt_len
128           1.00
256           1.00
512           1.01
1024          1.01
2048          1.00
4096          1.00

In [8]:
models_df_dict['qwen'].round(2)

           total_time_s                  tokens_per_s                   \
               baseline compiled speedup     baseline compiled speedup
prompt_len
128               12.79     6.16    2.08        10.01    20.79    2.08
256               12.20     6.37    1.92        10.49    20.09    1.92
512               12.34     6.85    1.80        10.37    18.69    1.80
1024              12.49     7.66    1.63        10.25    16.71    1.63
2048              13.61     9.44    1.44         9.40    13.56    1.44
4096              16.83    13.47    1.25         7.61     9.50    1.25

           max_mem_alloc_mb                  max_mem_reserved_mb           \
                   baseline compiled speedup            baseline compiled
prompt_len
128                 3914.37  3942.15    1.01              4504.0   4530.0
256                 3929.37  3971.16    1.01              4530.0   4582.0
512                 3984.84  4031.43    1.01              4530.0   4526.0
1024                4048.42  4145.18    1.02              4472.0   4472.0
2048                4212.96  4377.22    1.04              4474.0   4472.0
4096                4542.03  4841.95    1.07              4616.0   5036.0


           speedup
prompt_len
128           1.01
256           1.01
512           1.00
1024          1.00
2048          1.00
4096          1.09